FROM --platform=linux/amd64 ghcr.io/cross-rs/aarch64-unknown-linux-gnu:main

RUN dpkg --add-architecture arm64 && \
    DEBIAN_FRONTEND=noninteractive apt-get \
      -o Acquire::CompressionTypes::Order::=gz \
      update && \
    DEBIAN_FRONTEND=noninteractive apt-get \
      -o Acquire::CompressionTypes::Order::=gz \
      -y \
      --no-install-recommends \
      install \
        clang \
        cmake \
        pkg-config \
        libfontconfig1-dev:arm64 \
        libfreetype6-dev:arm64 \
        libwayland-dev:arm64 \
        libx11-dev:arm64 \
        libxcb1-dev:arm64 \
        libxkbcommon-dev:arm64 \
        libxkbcommon-x11-dev:arm64 \
        libvulkan-dev:arm64
