FROM --platform=linux/amd64 ghcr.io/cross-rs/armv7-unknown-linux-gnueabihf:main

RUN dpkg --add-architecture armhf && \
    DEBIAN_FRONTEND=noninteractive apt-get \
      -o Acquire::CompressionTypes::Order::=gz \
      update && \
    DEBIAN_FRONTEND=noninteractive apt-get \
      -o Acquire::CompressionTypes::Order::=gz \
      -y \
      --no-install-recommends \
      install \
        clang \
        cmake \
        pkg-config \
        libfontconfig1-dev:armhf \
        libfreetype6-dev:armhf \
        libwayland-dev:armhf \
        libx11-dev:armhf \
        libxcb1-dev:armhf \
        libxkbcommon-dev:armhf \
        libxkbcommon-x11-dev:armhf \
        libvulkan-dev:armhf
