FROM --platform=linux/amd64 ghcr.io/cross-rs/x86_64-unknown-linux-gnu:main

RUN DEBIAN_FRONTEND=noninteractive apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get -y --no-install-recommends install \
    clang \
    cmake \
    pkg-config \
    libfontconfig1-dev \
    libfreetype6-dev \
    libwayland-dev \
    libx11-dev \
    libxcb1-dev \
    libxkbcommon-dev \
    libxkbcommon-x11-dev \
    libvulkan-dev
